// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkuwseKCk3YNi0hE_kdv4d_3uV9eEEoGw',
    appId: '1:1004007704500:web:30c712a1b7d200ed35d4e1',
    messagingSenderId: '1004007704500',
    projectId: 'my-tasks-c1f32',
    authDomain: 'my-tasks-c1f32.firebaseapp.com',
    storageBucket: 'my-tasks-c1f32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNwBBJM9sEeMU87Dx6LEe3ZgxtVjbyb9k',
    appId: '1:1004007704500:android:89ab014af63b169935d4e1',
    messagingSenderId: '1004007704500',
    projectId: 'my-tasks-c1f32',
    storageBucket: 'my-tasks-c1f32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG7QMQ2ObqlKTJAJeXZJ63zz5Mndlm-bE',
    appId: '1:1004007704500:ios:36315d96c5515ad635d4e1',
    messagingSenderId: '1004007704500',
    projectId: 'my-tasks-c1f32',
    storageBucket: 'my-tasks-c1f32.firebasestorage.app',
    iosBundleId: 'com.example.myTasks',
  );
}
